#! /bin/sh
# pkg-config wrapper for cross-building
# Sets pkg-config search path to target arch path only.

triplet=`basename $0 | sed -e 's:-pkg-config::'`

# If LIBDIR is defined, it no longer searches system locations.
# PATH is always checked before LIBDIR.
PKG_CONFIG_LIBDIR=${PKG_CONFIG_LIBDIR}:/usr/lib/${triplet}/pkgconfig:/usr/${triplet}/lib/pkgconfig \
pkg-config $@
RET=$?
if true
then
  OUT=$(pkg-config $@)
  echo "PATH: $PKG_CONFIG_PATH" >&2
  echo "LIBDIR: $PKG_CONFIG_LIBDIR" >&2
  echo "pkg-config $@ -> $RET [$OUT]" >&2
fi
exit ${RET}
